name: Run Robot Framework Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Start FastAPI Application
        run: |
          source venv/bin/activate
          uvicorn main:app --host 0.0.0.0 --port 8000 &
          sleep 5  # Give the server time to start

      - name: Run Robot Framework Tests
        run: |
          source venv/bin/activate
          robot --outputdir results tests/api_tests.robot

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: robot-test-results
          path: results/
          retention-days: 7 # Keep test results for 7 days
